// Code generated by scripts/generate_go_funcs; DO NOT EDIT.
package jq

import (
	"errors"
	"fmt"
)

func asInt(key interface{}) (int, error) {
	var ok bool

	if _, ok = key.(int); ok {
		return key.(int), nil
	} else if _, ok = key.(float64); ok {
		return int(key.(float64)), nil
	} else if _, ok = key.(uint64); ok {
		return int(key.(uint64)), nil
	}

	return 0, errors.New(fmt.Sprintf("key %v not int type", key))
}

func asString(key interface{}) (string, error) {
	var ok bool
	var val string

	if val, ok = key.(string); ok {
		return val, nil
	}

	return "", errors.New(fmt.Sprintf("key %v not string type", key))
}

func (j *JSON) nestedGetKey(keys []interface{}) interface{} {
	var e error
	var tryInt int
	var tryString string
	var v interface{}
	var val interface{} = j.blob

	for _, key := range keys {
		if tryString, e = asString(key); e == nil {
			v = val.(map[string]interface{})[tryString]
		} else if tryInt, e = asInt(key); e == nil {
			v = val.([]interface{})[tryInt]
		}
		if e != nil {
			panic(errors.New(fmt.Sprintf("key %v not found", keys)))
		}
		val = v
	}

	return val
}

func (j *JSON) Get(key ...interface{}) interface{} {
	return j.nestedGetKey(key)
}

func (j *JSON) GetArray(key ...interface{}) []interface{} {
	return j.nestedGetKey(key).([]interface{})
}

func (j *JSON) GetMap(key ...interface{}) map[string]interface{} {
	return j.nestedGetKey(key).(map[string]interface{})
}

func (j *JSON) GetBool(key ...interface{}) bool {
	return j.nestedGetKey(key).(bool)
}

func (j *JSON) GetBoolArray(key ...interface{}) []bool {
	return j.nestedGetKey(key).([]bool)
}

func (j *JSON) GetBoolMap(key ...interface{}) map[string]bool {
	return j.nestedGetKey(key).(map[string]bool)
}

func (j *JSON) GetFloat32(key ...interface{}) float32 {
	var ok bool
	var val float32

	if val, ok = j.nestedGetKey(key).(float32); ok {
		return val
	}

	return float32(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetFloat32Array(key ...interface{}) []float32 {
	var ok bool
	var val = []float32{}

	if val, ok = j.nestedGetKey(key).([]float32); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, float32(v.(float64)))
	}

	return val
}

func (j *JSON) GetFloat32Map(key ...interface{}) map[string]float32 {
	var ok bool
	var val = map[string]float32{}

	if val, ok = j.nestedGetKey(key).(map[string]float32); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = float32(v.(float64))
	}

	return val
}

func (j *JSON) GetFloat64(key ...interface{}) float64 {
	var ok bool
	var val float64

	if val, ok = j.nestedGetKey(key).(float64); ok {
		return val
	}

	return float64(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetFloat64Array(key ...interface{}) []float64 {
	var ok bool
	var val = []float64{}

	if val, ok = j.nestedGetKey(key).([]float64); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, float64(v.(float64)))
	}

	return val
}

func (j *JSON) GetFloat64Map(key ...interface{}) map[string]float64 {
	var ok bool
	var val = map[string]float64{}

	if val, ok = j.nestedGetKey(key).(map[string]float64); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = float64(v.(float64))
	}

	return val
}

func (j *JSON) GetInt(key ...interface{}) int {
	var ok bool
	var val int

	if val, ok = j.nestedGetKey(key).(int); ok {
		return val
	}

	return int(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetIntArray(key ...interface{}) []int {
	var ok bool
	var val = []int{}

	if val, ok = j.nestedGetKey(key).([]int); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, int(v.(float64)))
	}

	return val
}

func (j *JSON) GetIntMap(key ...interface{}) map[string]int {
	var ok bool
	var val = map[string]int{}

	if val, ok = j.nestedGetKey(key).(map[string]int); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = int(v.(float64))
	}

	return val
}

func (j *JSON) GetInt16(key ...interface{}) int16 {
	var ok bool
	var val int16

	if val, ok = j.nestedGetKey(key).(int16); ok {
		return val
	}

	return int16(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetInt16Array(key ...interface{}) []int16 {
	var ok bool
	var val = []int16{}

	if val, ok = j.nestedGetKey(key).([]int16); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, int16(v.(float64)))
	}

	return val
}

func (j *JSON) GetInt16Map(key ...interface{}) map[string]int16 {
	var ok bool
	var val = map[string]int16{}

	if val, ok = j.nestedGetKey(key).(map[string]int16); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = int16(v.(float64))
	}

	return val
}

func (j *JSON) GetInt32(key ...interface{}) int32 {
	var ok bool
	var val int32

	if val, ok = j.nestedGetKey(key).(int32); ok {
		return val
	}

	return int32(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetInt32Array(key ...interface{}) []int32 {
	var ok bool
	var val = []int32{}

	if val, ok = j.nestedGetKey(key).([]int32); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, int32(v.(float64)))
	}

	return val
}

func (j *JSON) GetInt32Map(key ...interface{}) map[string]int32 {
	var ok bool
	var val = map[string]int32{}

	if val, ok = j.nestedGetKey(key).(map[string]int32); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = int32(v.(float64))
	}

	return val
}

func (j *JSON) GetInt64(key ...interface{}) int64 {
	var ok bool
	var val int64

	if val, ok = j.nestedGetKey(key).(int64); ok {
		return val
	}

	return int64(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetInt64Array(key ...interface{}) []int64 {
	var ok bool
	var val = []int64{}

	if val, ok = j.nestedGetKey(key).([]int64); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, int64(v.(float64)))
	}

	return val
}

func (j *JSON) GetInt64Map(key ...interface{}) map[string]int64 {
	var ok bool
	var val = map[string]int64{}

	if val, ok = j.nestedGetKey(key).(map[string]int64); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = int64(v.(float64))
	}

	return val
}

func (j *JSON) GetString(key ...interface{}) string {
	return j.nestedGetKey(key).(string)
}

func (j *JSON) GetStringArray(key ...interface{}) []string {
	var ok bool
	var val = []string{}

	if val, ok = j.nestedGetKey(key).([]string); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, v.(string))
	}

	return val
}

func (j *JSON) GetStringMap(key ...interface{}) map[string]string {
	var ok bool
	var val = map[string]string{}

	if val, ok = j.nestedGetKey(key).(map[string]string); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = v.(string)
	}

	return val
}

func (j *JSON) GetUint(key ...interface{}) uint {
	var ok bool
	var val uint

	if val, ok = j.nestedGetKey(key).(uint); ok {
		return val
	}

	return uint(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetUintArray(key ...interface{}) []uint {
	var ok bool
	var val = []uint{}

	if val, ok = j.nestedGetKey(key).([]uint); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, uint(v.(float64)))
	}

	return val
}

func (j *JSON) GetUintMap(key ...interface{}) map[string]uint {
	var ok bool
	var val = map[string]uint{}

	if val, ok = j.nestedGetKey(key).(map[string]uint); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = uint(v.(float64))
	}

	return val
}

func (j *JSON) GetUint16(key ...interface{}) uint16 {
	var ok bool
	var val uint16

	if val, ok = j.nestedGetKey(key).(uint16); ok {
		return val
	}

	return uint16(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetUint16Array(key ...interface{}) []uint16 {
	var ok bool
	var val = []uint16{}

	if val, ok = j.nestedGetKey(key).([]uint16); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, uint16(v.(float64)))
	}

	return val
}

func (j *JSON) GetUint16Map(key ...interface{}) map[string]uint16 {
	var ok bool
	var val = map[string]uint16{}

	if val, ok = j.nestedGetKey(key).(map[string]uint16); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = uint16(v.(float64))
	}

	return val
}

func (j *JSON) GetUint32(key ...interface{}) uint32 {
	var ok bool
	var val uint32

	if val, ok = j.nestedGetKey(key).(uint32); ok {
		return val
	}

	return uint32(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetUint32Array(key ...interface{}) []uint32 {
	var ok bool
	var val = []uint32{}

	if val, ok = j.nestedGetKey(key).([]uint32); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, uint32(v.(float64)))
	}

	return val
}

func (j *JSON) GetUint32Map(key ...interface{}) map[string]uint32 {
	var ok bool
	var val = map[string]uint32{}

	if val, ok = j.nestedGetKey(key).(map[string]uint32); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = uint32(v.(float64))
	}

	return val
}

func (j *JSON) GetUint64(key ...interface{}) uint64 {
	var ok bool
	var val uint64

	if val, ok = j.nestedGetKey(key).(uint64); ok {
		return val
	}

	return uint64(j.nestedGetKey(key).(float64))
}

func (j *JSON) GetUint64Array(key ...interface{}) []uint64 {
	var ok bool
	var val = []uint64{}

	if val, ok = j.nestedGetKey(key).([]uint64); ok {
		return val
	}

	for _, v := range j.nestedGetKey(key).([]interface{}) {
		val = append(val, uint64(v.(float64)))
	}

	return val
}

func (j *JSON) GetUint64Map(key ...interface{}) map[string]uint64 {
	var ok bool
	var val = map[string]uint64{}

	if val, ok = j.nestedGetKey(key).(map[string]uint64); ok {
		return val
	}

	for k, v := range j.nestedGetKey(key).(map[string]interface{}) {
		val[k] = uint64(v.(float64))
	}

	return val
}
